# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
	pod 'ObjectMapper'
	pod 'MBProgressHUD'
    pod 'IQKeyboardManagerSwift'
  # Pods for HRManager

end
